repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        exclude: ^backend/static/
# Note that this does not mix with git setup check-in LF check-out CRLF,
# see https://github.com/pre-commit/pre-commit-hooks#mixed-line-ending
    -   id: mixed-line-ending
        args: [--fix=lf]
        exclude: ^backend/static/
        exclude: |
                (?x)(
                    ^backend/static/|
                    ^backend/backups/|
                    ^backend/run/|
                    ^database/backups/|
                    ^database/data/
                )
# use black or autopep8 to automatically format files to pep8
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.6
        exclude: ^backend/apps/[a-z]*/migrations/[0-9A-z]*.py
#-   repo: https://gitlab.com/pycqa/flake8
#    rev: stable
#    hooks:
#    -   id: flake8
