repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        exclude: ^backend/static/
# use black or autopep8 to automatically format files to pep8
#-   repo: https://github.com/psf/black
#    rev: stable
#    hooks:
#    -   id: black
#-   repo: https://gitlab.com/pycqa/flake8
#    rev: stable
#    hooks:
#    -   id: flake8
