services:
  - docker

before_script:
 - docker-compose -f docker-compose.dev.yml -f docker-compose.prod.yml up -d --build

script:
 - ./deploy.sh
 - docker exec backend python3 manage.py test

after_script:
 - docker-compose down
