services:
  - docker

before_script:
 - ./scripts/write_envs_to_file.sh
 - ./deploy.sh
 - ./scripts/wait_for_backend.sh
 - docker logs $(docker ps | grep backend | awk 'END {print $16}')
 - docker logs $(docker ps | grep database | awk 'END {print $12}')


script:
 - bash scripts/check_website_availability.sh
 - docker exec backend python3 manage.py test

after_script:
 - docker-compose down
