services:
  - docker

before_script:
 - ./scripts/write_envs_to_file.sh
 - ./deploy.sh
 - ./scripts/wait_for_backend.sh
 - docker logs match4healthcare_backend_1
 - docker logs match4healthcare_database_1


script:
 - bash scripts/check_website_availability.sh
 - docker exec backend python3 manage.py test

after_script:
 - docker-compose down
