name: Test for existence of all translations
on: [push]

jobs:
  test:
    name: Test for existence of all translations
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - name: Install gettext
      run: sudo apt-get update && sudo apt-get install gettext
    - name: Cache python packages
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('./backend/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r ./backend/requirements.txt

    - name: Generate updated .po file
      run: django-admin makemessages -l en --no-location

    - name: Check for fuzzy translations
      run: bash -c 'if [ $(cat backend/locale/en/LC_MESSAGES/django.po | grep "#, fuzzy" | wc -l) -gt 0 ];
                    then echo "Unresolved fuzzy translations are present"; return 1; fi'

    - name: Check for missing translations
      # https://stackoverflow.com/a/14799019/3342058
      run: bash -c 'if [ $(awk '$NF == "msgstr \"\"" { c++ } END { print c }' FS="\n" RS= ./backend/locale/en/LC_MESSAGES/django.po) -gt 0 ]; 
                    then echo "Unresolved fuzzy translations are present"; return 1; fi'
