name: Test for existence of all translations
on: [push]

jobs:
  test:
    name: Test for existence of all translations
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - name: Install gettext
      run: sudo apt-get update && sudo apt-get install gettext
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r ./backend/requirements.txt
    - name: Cache python packages
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('./backend/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Generate updated .po file
      run: django-admin makemessages -l en --no-location

    - name: Check for fuzzy translations
      run: if [$(cat backend/locale/en/LC_MESSAGES/django.po | grep "#, fuzzy" | wc -l) -gt 0 ]; then echo "Unresolved fuzzy translations are present"; exit 1; fi